setting_schemas:
  section_moderator:

    forum_mod_can_delete_topics:
      priority: 530
      extends: true

    forum_mod_can_delete_posts:
      priority: 540
      extends: true

    forum_mod_can_edit_titles:
      extends: true
      priority: 550
