setting_schemas:
  forum_moderator:
    forum_mod_visible:
      priority: 500
      type: boolean
      default: true

    forum_mod_can_edit_titles:
      extends: true
      priority: 510

    forum_mod_can_edit_posts:
      extends: true
      priority: 520

    forum_mod_can_delete_topics:
      extends: true
      priority: 530

    forum_mod_can_delete_posts:
      extends: true
      priority: 540
