menus:
  common:
    navbar:
      forum:
        to: forum.index

  admin:
    navbar:
      forum:
        to: admin.forum.section.index
        submenu:
          section:
            to: admin.forum.section.index

          group_permissions:
            to: admin.forum.group_permissions.index

          moderator:
            to: admin.forum.moderator.index

    nntp:
      forum:
        to: admin.nntp.create.forum
