setting_schemas:
  section_moderator:

    forum_mod_visible:
      priority: 500
      type: boolean
      default: true

    forum_mod_can_pin_topic:
      priority: 510
      extends: true

    forum_mod_can_edit_posts:
      priority: 520
      extends: true

    forum_mod_can_delete_topics:
      priority: 530
      extends: true

    forum_mod_can_hard_delete_topics:
      priority: 540
      extends: true

    forum_mod_can_see_hard_deleted_topics:
      priority: 550
      extends: true

    forum_mod_can_edit_titles:
      extends: true
      priority: 560

    forum_mod_can_close_topic:
      extends: true
      priority: 570
