setting_groups:
  forum: ~

  forum_general:
    parent: forum


setting_schemas:
  global:
    topics_per_page:
      type: number
      group_key: forum_general
      category_key: forum
      default: 30

    topic_title_min_length:
      type: number
      group_key: forum_general
      category_key: topic
      default: 3

    posts_per_page:
      type: number
      group_key: forum_general
      category_key: topic
      default: 25
