setting_groups:
  forum: ~

  forum_editor:
    parent: forum


setting_schemas:
  global:
    general_abuse_report_section:
      priority: 10
      group_key: abuse_reports
      category_key: forum
      type: dropdown
      values: forum_sections
      default: ~

    forum_topic_title_min_length:
      type: number
      group_key: forum_editor
      category_key: topic
      default: 10

    forum_topic_title_max_length:
      type: number
      group_key: forum_editor
      category_key: topic
      default: 100

    forum_post_min_length:
      type: number
      group_key: forum_editor
      category_key: post
      default: 10

    forum_post_max_images:
      type: number
      group_key: forum_editor
      category_key: post
      default: 100

    forum_post_max_emojis:
      type: number
      group_key: forum_editor
      category_key: post
      default: 20

    forum_edit_max_time:
      priority: 40
      group_key: forum_editor
      category_key: topic
      type: number
      default: 30

    forum_reply_old_post_threshold:
      priority: 50
      group_key: forum_editor
      category_key: topic
      type: number
      default: 30

    forum_show_post_interval:
      priority: 60
      group_key: forum_editor
      category_key: topic
      type: number
      default: 7
