setting_schemas:
  usergroup:

    forum_can_view:
      priority: 10
      category_key: forum
      type: boolean
      default: true

    forum_can_reply:
      priority: 20
      category_key: forum
      type: boolean
      default: false

    forum_can_start_topics:
      priority: 30
      category_key: forum
      type: boolean
      default: false

    forum_edit_max_time:
      priority: 40
      category_key: forum
      type: number
      default: 30

    forum_can_close_topic:
      priority: 50
      category_key: forum
      type: boolean
      default: false

    forum_mod_can_pin_topic:
      priority: 500
      category_key: perm_moderator
      type: boolean
      default: false

    forum_mod_can_edit_posts:
      priority: 510
      category_key: perm_moderator
      type: boolean
      default: false

    forum_mod_can_delete_topics:
      priority: 520
      category_key: perm_moderator
      type: boolean
      default: false

    forum_mod_can_hard_delete_topics:
      priority: 530
      category_key: perm_moderator
      type: boolean
      default: false

    forum_mod_can_see_hard_deleted_topics:
      priority: 540
      category_key: perm_moderator
      type: boolean
      default: false

    forum_mod_can_edit_titles:
      priority: 550
      category_key: perm_moderator
      type: boolean
      default: false

    forum_mod_can_close_topic:
      priority: 560
      category_key: perm_moderator
      type: boolean
      default: false
