setting_schemas:
  usergroup:

    forum_show:
      type: boolean
      default: true
      category: forum
      priority: 0

    forum_read_topics:
      type: boolean
      default: true
      category: forum
      priority: 0

    forum_reply_topics:
      type: boolean
      default: true
      category: forum
      priority: 0

    forum_start_topics:
      type: boolean
      default: true
      category: forum
      priority: 0
